### ISSUE TITLE
Apt update fails

### ISSUE THREAD

**Issue by ravener** [Neo-Oli/termux-ubuntu#100]
I just installed this and it seems cool but i when i use apt package manager to update the packages list i get
```
root@localhost:~# apt update
Reading package lists... Done
E: Method gave invalid 400 URI Failure message: Failed to set new user ids - setresuid (1: Operation not permitted)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
root@localhost:~#
```

**Comment by diehard88** [comment]
https://github.com/EXALAB/AnLinux-App/issues/36

**Comment by ravener** [comment]
@diehard88 that issue shows "function not implemented" errors, mine is a "operation not permitted" plus there's no solution in there

**Comment by mylove90** [comment]
root@localhost:~# apt-get update
Err:1 http://ports.ubuntu.com/ubuntu-ports disco InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:2 http://ports.ubuntu.com/ubuntu-ports disco-updates InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:3 http://ports.ubuntu.com/ubuntu-ports disco-backports InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Err:4 http://ports.ubuntu.com/ubuntu-ports disco-security InRelease
  Temporary failure resolving 'ports.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/disco/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/disco-updates/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/disco-backports/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/disco-security/InRelease  Temporary failure resolving 'ports.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@localhost:~#

**Comment by ravener** [comment]
It fixed itself suddenly after a long time, must've been related to proot.
