### ISSUE TITLE
dpkg interrupted after the certain time

### ISSUE THREAD

**Issue by SharifPoetra** [Neo-Oli/termux-ubuntu#112]
Before when I run apt command, all works fine but after in certain time I got the error says
```bash
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```
But when I run `dpkg --configure -a` I got the new error says
```bash
dpkg: error: error creating new backup file '/var/lib/dpkg/status-old': Operation not permitted
```
Please help me how to fix this? thanks in further!

**Comment by SharifPoetra** [comment]
Looks like no one here :/

**Comment by Allan-sketch** [comment]
In which conditions have you got errors to pkg like what have you done.

**Comment by SharifPoetra** [comment]
Lmao after almost two years, only now got a reply. I have forget what was really happen.
