### ISSUE TITLE
Installing sudo?

### ISSUE THREAD

**Issue by Daksh777** [Neo-Oli/termux-ubuntu#114]
How can I use sudo in this? It's not installed.

**Comment by aletisunil** [comment]
when u install ubuntu,
first execute these commands
apt update
apt upgrade
apt install sudo

**Comment by Daksh777** [comment]
It says sudo not found

**Comment by chy6** [comment]
mengistall sudo

**Comment by phanirithvij** [comment]
No need to install sudo because you are root. I think if you setup non root users then you can use sudo from there.

**Comment by Agvantibo** [comment]
Apt install tsu, n00bs!
