### ISSUE TITLE
Ping does not work

### ISSUE THREAD

**Issue by RupankarGhosh** [Neo-Oli/termux-ubuntu#12]
there is no module named ping in Ubuntu here.Add some module for ping

**Comment by casept** [comment]
AFAIK ping requires usage of raw sockets, which you need root for anyways (and at that point why not use something like [linux deploy](https://github.com/meefik/linuxdeploy))?

**Comment by RupankarGhosh** [comment]
@casept Now I have ping with busybox and it works fine ,also network tools like ifconfig :blush:
