### ISSUE TITLE
404?

### ISSUE THREAD

**Issue by Agvantibo** [Neo-Oli/termux-ubuntu#132]
The output:

bash ubuntu.sh
downloading ubuntu-image
--2020-07-23 12:37:28--  https://partner-images.canonical.com/core/disco/current/ubuntu-disco-core-cloudimg-arm64-root.tar.gz
Resolving partner-images.canonical.com... 91.189.88.147
Connecting to partner-images.canonical.com|91.189.88.147|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-23 12:37:28 ERROR 404: Not Found.

decompressing ubuntu image
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
fixing nameserver, otherwise it can't connect to the internet
ubuntu.sh: line 33: etc/resolv.conf: No such file or directory
writing launch script
fixing shebang of start-ubuntu.sh
making start-ubuntu.sh executable
You can now launch Ubuntu with the ./start-ubuntu.sh script

Probably not ok

**Comment by imahx2074** [comment]
Also have same problem

**Comment by Agvantibo** [comment]
Fixed! Replace the wget tar in Ubuntu.sh with wget "https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-${archurl}-root.tar.gz" -O $tarball
