### ISSUE TITLE
ifconfig is not working

### ISSUE THREAD

**Issue by T4P4N** [Neo-Oli/termux-ubuntu#14]
ifconfig is not working

**Comment by RupankarGhosh** [comment]
use "busybox ifconfig".There is also not ping without busybox

**Comment by diehard88** [comment]
i can't find busybox, though there is a toybox.

i can't run ping, ifconfig, etc

**Comment by sasmitadn** [comment]
Use commmand
apt-get install net-tools

And you can use ifconfig
