### ISSUE TITLE
Support for i386, i686

### ISSUE THREAD

**Issue by brysgo** [Neo-Oli/termux-ubuntu#18]
Thanks for this, it works great!

I had to add a couple if statements for it to with on my Chromebook Pixel 2 (i686). I the Ubuntu architecture that I used was i386. I can make a PR if you'd like but the change is pretty small.

**Comment by Neo-Oli** [comment]
Since I can't test the script for i386 and i686 I'd appreciate a Pull Request.

**Comment by brysgo** [comment]
Great I will do this after work
