### ISSUE TITLE
Cannot Update Repository (fixed, check your dns) usually its blocked by admin.

### ISSUE THREAD

**Issue by azispratama92** [Neo-Oli/termux-ubuntu#28]
Already edit the resolv.conf file using this value:

domain http://ports.ubuntu.com/ubuntu-ports/pool/main/p/perl/perl_5.24.1-2ubuntu1_armhf.deb
nameserver 8.8.8.8
nameserver 8.8.4.4

But it seems still wont update, what todo?

**Comment by azispratama92** [comment]
![](https://i.imgur.com/N8G2Vkq.png)

**Comment by azispratama92** [comment]
Fixed, please check your wifi network either it was blocked or not by the admin, 

In my school the admin blocked the DNS, that's caused the apt-get update command failure to reach Ubuntu Repo. 

Big thanks for the developers :relaxed:

**Comment by kanxck** [comment]
Note fix
