### ISSUE TITLE
Can i used Ubuntu Zesty Z. Instead Artfull?

### ISSUE THREAD

**Issue by azispratama92** [Neo-Oli/termux-ubuntu#29]
How to used Zasty Image Instead of Artfull Ardvard? 

Recently i read some blog post about termux Ubuntu, some of the writer, they are mention About Ubuntu Zasty instead of Artfull. 

Maybe i can update repository in termux if i used older version of Ubuntu? ![](https://i.imgur.com/aDjdxSk.png)

**Comment by Neo-Oli** [comment]
Sure, just change the link on Line 11, 13, 15, 17 and 19.

**Comment by azispratama92** [comment]
Nvm its turns out that my university blocked the dns, when i tested using 3g network i can update repo without any error, 

Thanks you Sir :wink:
