### ISSUE TITLE
Git error on binded folder.: unable to write sha1 filename

### ISSUE THREAD

**Issue by orlleite** [Neo-Oli/termux-ubuntu#30]
Hi, That's great project and I'm liking it.

I got a sdcard/storage bind folder using a file inside the binds folder. It looks like this:

    command+=" -b $HOME/storage/downloads"
    command+=" -b $HOME/storage/shared/Projects"

It's working except when I'm trying to use git clone inside one of these folders. I got an error
`error: unable to write sha1 filename /data/data/com.termux/files/home/storage/shared/Projects/....pack: No such file or directory
fatal: cannot store pack file
fatal: index-pack failed`

If I git clone out of these binded folders, I can have a working repo, but when I move it to one of these folders I got many lines like this:
`mv: preserving times for 'projects/.../.git/branches': Operation not permitted`

And after it, git thinks I had changed some files of this repository. The way I found to workaround it was git clone at termux terminal and only after that starting ubuntu. I didn't test if pull/push is working yet. I think this other project has something relate to this problem [https://github.com/corbinlc/GNURootDebian/issues/105](url).

**Comment by Neo-Oli** [comment]
This is because the internal sd card is filesystem that doesn't support certain attributes. It's not a problem specific to termux-ubuntu, these same errors occur if you try to do it in regular termux.
