### ISSUE TITLE
need help getting 64-bit running

### ISSUE THREAD

**Issue by brysgo** [Neo-Oli/termux-ubuntu#39]
Hey @Neo-Oli - thanks again for this stuff, I find myself coming back to it often. I am trying to install 64 bit ubuntu on my chromebook pixel 2 (i686) so I made some small changes to your install script. I get an error from proot that it can't run 64 bit programs.

```diff
		amd64)
			archurl="amd64" ;;
+		i686)
+			archurl="amd64" ;;
+		i386)
-		i*86)
			archurl="i386" ;;
		*)
			echo "unknown architecture"; exit 1 ;;
		esac
+		wget "https://partner-images.canonical.com/core/cosmic/current/ubuntu-cosmic-core-cloudimg-${archurl}-root.tar.gz" -O $tarball
-		wget "https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-${archurl}-root.tar.gz" -O $tarball
	fi
	cur=`pwd`
```

![screenshot 2018-05-13 at 2 24 30 am](https://user-images.githubusercontent.com/57716/39964592-7f8bcf6c-5655-11e8-9354-f14b9a9c634e.png)

**Comment by Neo-Oli** [comment]
Why would you expect this to work? You have 32 bit CPU you can't run 64 bit programs. Most of all not amd64 programs

**Comment by brysgo** [comment]
@Neo-Oli - I don't have a 32 bit cpu! In fact, I'm running a 64 bit OS

**Comment by brysgo** [comment]
![screenshot 2018-05-13 at 8 29 49 am](https://user-images.githubusercontent.com/57716/39967376-f75e5848-5687-11e8-9ad4-19c6453753d3.png)

**Comment by brysgo** [comment]
But I didn't know amd64 was not the same as x86_64, now I do, but I still think it will not work.

**Comment by brysgo** [comment]
Seems like a Termux problem though,

In crosh:

```bash
crosh> uname -a
Linux localhost 3.14.0 #1 SMP PREEMPT Tue May 8 22:14:52 PDT 2018 x86_64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz GenuineIntel GNU/Linux
```

In termux:

```
$ uname -a
Linux localhost 3.14.0 #1 SMP PREEMPT Tue May 8 22:14:52 PDT 2018 i686 Android
```

**Comment by brysgo** [comment]
Or more likely the android build.

**Comment by diehard88** [comment]
what about this?

![](https://i.imgur.com/299wOJv.jpg)

**Comment by brysgo** [comment]
I appreciate the help, I figured out. The Android layer on my Chromebook was 32 bit even though chrome is is 64 bit. It was a documented issue with Chromebook Android, apollogies for the noise.
