### ISSUE TITLE
proot info: vpid 1: terminated with signal 7

### ISSUE THREAD

**Issue by Hax4us** [Neo-Oli/termux-ubuntu#4]
![intex aqua trend_2017-08-02-17-12-17](https://user-images.githubusercontent.com/30441647/28872428-bce10a78-77a6-11e7-9496-7aad6b57252c.png)
Solve plz...

**Comment by Neo-Oli** [comment]
That looks very weird. Perhabs the ubuntu.tar.gz is damaged. Could you try again?

**Comment by Hax4us** [comment]
Issue solved by substituting tar :D

**Comment by maliqmc** [comment]
proot info: vpid 1: terminated with signal 11

**Comment by maliqmc** [comment]
when you want ./start-ubuntu it actually comes out. info info: vpid1: terminated with signal 11 why please help me please

**Comment by KimYangOfCat** [comment]
![image](https://user-images.githubusercontent.com/32960305/76164924-aed99700-618d-11ea-9494-bd904bae14b2.png)
when  I launch ubuntu, I got this info~
I have tried  installing again and launch again, but it didn't work~
