### ISSUE TITLE
Transferring files between ubuntu and android file system

### ISSUE THREAD

**Issue by zcatav** [Neo-Oli/termux-ubuntu#41]
Hi,
How can I do transfer files from Ubuntu, to outside of proot environment or vice versa?
Thanks in advances.

**Comment by diehard88** [comment]
the ubuntu file system is contained under ubuntu-fs.

termux is the super set.

**Comment by zcatav** [comment]
Thanks, I got it.
I'm trying now to install Firebird on Ubuntu. But it fails due to adduser not works as usual.
