### ISSUE TITLE
/proc is not mounted?

### ISSUE THREAD

**Issue by diehard88** [Neo-Oli/termux-ubuntu#45]
./start-ubuntu.sh
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20251
groups: cannot find name for group ID 50251

root@localhost:~# ps -aT
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
root@localhost:~#
root@localhost:~#
root@localhost:~#
root@localhost:~#
root@localhost:~# mount
rootfs on / type rootfs (ro,seclabel,size=1651280k,nr_inodes=412820)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,seclabel,size=1718764k,nr_inodes=429691,mode=755)
devpts on /dev/pts type devpts (rw,relatime,seclabel,mode=600)
none on /dev/cpuctl type cgroup (rw,relatime,cpu)
none on /dev/cpuset type cgroup (rw,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
sysfs on /sys type sysfs (rw,relatime,seclabel)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime,seclabel)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime,seclabel)
pstore on /sys/fs/pstore type pstore (rw,relatime,seclabel)
/dev/block/dm-0 on /system type ext4 (ro,relatime,seclabel,norecovery)
none on /acct type cgroup (rw,relatime,cpuacct)
tmpfs on /mnt type tmpfs (rw,relatime,seclabel,size=1718764k,nr_inodes=429691,mode=755,gid=1000)
tmpfs on /mnt/secure type tmpfs (rw,relatime,seclabel,size=1718764k,nr_inodes=429691,mode=700)
/data/knox/sdcard/150 on /mnt/knox/default/emulated/150 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6,userid=150,reserved=20MB)
/data/knox/sdcard/150 on /mnt/knox/read/emulated/150 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=23,userid=150,reserved=20MB)
/data/knox/sdcard/150 on /mnt/knox/write/emulated/150 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7,userid=150,reserved=20MB)
/data/media on /mnt/runtime/default/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,reserved=20MB)
/data/media on /mnt/runtime/read/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,reserved=20MB)
/data/media on /mnt/runtime/write/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,reserved=20MB)
/data/knox/secure_fs/enc_media on /mnt/shell/enc_emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1000,fsgid=1000,gid=9997,multiuser,reserved=20MB)
none on /config type configfs (rw,relatime)
/dev/block/bootdevice/by-name/cache on /cache type ext4 (rw,nosuid,nodev,noatime,seclabel,journal_checksum,journal_async_commit,noauto_da_alloc)
/dev/block/bootdevice/by-name/persist on /persist type ext4 (rw,nosuid,nodev,noatime,seclabel)
/dev/block/bootdevice/by-name/efs on /efs type ext4 (rw,nosuid,nodev,noatime,seclabel,journal_checksum,journal_async_commit,noauto_da_alloc)
/dev/block/bootdevice/by-name/dsp on /dsp type ext4 (ro,nosuid,nodev,relatime,seclabel,data=ordered)
/dev/block/bootdevice/by-name/apnhlos on /firmware type vfat (ro,relatime,context=u:object_r:firmware_file:s0,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro)
/dev/block/bootdevice/by-name/modem on /firmware-modem type vfat (ro,relatime,context=u:object_r:firmware_file:s0,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro)
/dev/block/dm-1 on /data type ext4 (rw,nosuid,nodev,noatime,seclabel,journal_checksum,journal_async_commit,noauto_da_alloc)
/data/knox/data_de/150 on /data/user_de/150 type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_sig=694146088d1555d7,userid=150,sdp_enabled,partition_id=0,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/misc_de/150 on /data/misc_de/150 type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_sig=694146088d1555d7,userid=150,sdp_enabled,partition_id=1,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/system_de/150 on /data/system_de/150 type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_sig=694146088d1555d7,userid=150,sdp_enabled,partition_id=2,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/data/150 on /data/user/150 type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_sig=06d4724190970209,userid=150,sdp_enabled,partition_id=3,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/sdcard/150 on /data/knox/sdcard/150 type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_sig=06d4724190970209,userid=150,sdp_enabled,partition_id=4,dlp_enabled,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/misc_ce/150 on /data/misc_ce/150 type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_sig=06d4724190970209,userid=150,sdp_enabled,partition_id=5,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/system_ce/150 on /data/system_ce/150 type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_sig=06d4724190970209,userid=150,sdp_enabled,partition_id=6,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/secure_fs/enc_user on /data/enc_user type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_fnek_sig=a692cd761731acfd,ecryptfs_sig=a692cd761731acfd,userid=0,sdp_enabled,partition_id=7,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
/data/knox/secure_fs/enc_media on /data/knox/secure_fs/enc_media type ecryptfs (rw,nodev,relatime,seclabel,ecryptfs_fnek_sig=a692cd761731acfd,ecryptfs_sig=a692cd761731acfd,userid=0,sdp_enabled,partition_id=8,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_enable_cc,ecryptfs_passthrough,base=,label=)
tmpfs on /storage type tmpfs (rw,relatime,seclabel,size=1718764k,nr_inodes=429691,mode=755,gid=1000)
/data/media on /storage/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,reserved=20MB)
/data/knox/sdcard/150 on /storage/emulated/150 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7,userid=150,reserved=20MB)
tmpfs on /storage/self type tmpfs (rw,relatime,seclabel,size=1718764k,nr_inodes=429691,mode=755,gid=1000)
root@localhost:~#

`test`

**Comment by diehard88** [comment]
troubleshooting steps I followed or shot:

1) I removed the termux-ubuntu folder and cloned it again from github.
2) installation with ./ubuntu.sh; smooth and error free;
3) launching with ./start-ubuntu.sh without errors;
4) yet the /proc not mounted error persists....

I believe I am at fault because I was  messing around with adb and some libs.
Before that I never ran into this issue.
I have three other androids where termux-ubuntu is operational.


mercy.

**Comment by casept** [comment]
Are you running android 8 or later? Google has updated the seccomp policies for android, so that apps can't access certain `/proc` entries. See https://github.com/termux/termux-app/issues/299 and https://android-developers.googleblog.com/2017/07/seccomp-filter-in-android-o.html for details.

**Comment by diehard88** [comment]
yep....   thanks!
