### ISSUE TITLE
architecture discrepancy

### ISSUE THREAD

**Issue by diehard88** [Neo-Oli/termux-ubuntu#47]
root@localhost:~# uname -a
Linux localhost 3.18.71-13482624 #1 SMP PREEMPT Fri May 4 20:47:19 KST 2018 aarch64 aarch64 aarch64 GNU/Linux

root@localhost:~#
root@localhost:~# dpkg --print-architecture
arm64

aarch64 or arm64?

probably both?

**Comment by casept** [comment]
Debian calls calls it arm64, while the kernel calls it aarch64. Both refer to the same architecture.

**Comment by diehard88** [comment]
thanks.

\

**Comment by diehard88** [comment]
@casept 

some feedback.

/system/bin/getprop

[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [greatqltecs]
