### ISSUE TITLE
FFmpeg Not working

### ISSUE THREAD

**Issue by kiam001** [Neo-Oli/termux-ubuntu#82]
ffmpeg: error while loading shared libraries: libx264.so.152: cannot enable executable stack as shared object requires: Permission denied

**Comment by kiam001** [comment]
Fresh Install

apt update
apt install ffmpeg -y

**Comment by archisman-panigrahi** [comment]
Same issue in Ubuntu 20.04.

I have `libx264.so.155` instead of 152.
It seems that this is a bug in Ubuntu's ARM images.

**Comment by kiam001** [comment]
think problem is slowed i rimender last time it works
