### ISSUE TITLE
Desktop Environment(GUI)

### ISSUE THREAD

**Issue by cr4shcod3** [Neo-Oli/termux-ubuntu#9]
I tried installing LXDE, Cinnamon, Mate, KDE, XFCE, Gnome and i think it's not compatible

**Comment by Neo-Oli** [comment]
Yeah android doesn't have an X Server, so you can't run Desktop Environments.

**Comment by ChristianSilvermoon** [comment]
Android can run a display server via [XServer XSDL](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjNrsWls6nYAhWL5IMKHdz_DQMQFggpMAA&url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dx.org.server%26hl%3Den&usg=AOvVaw0soT4BZNrOs1a2IJxFdBtR), exporting the `$DISPLAY` as normal will allow the use of graphical programs.

I have tested this with `icewm`, which functions just fine.

**Comment by ErbDroid** [comment]
@ChristianSilvermoon I have Ubuntu installed in termux, LXDE installed and just installed Xserver XADL apk as well, how do you use the Xserver app to view my Ubuntu in termux? Thank you for your help

**Comment by ogahozy** [comment]
> @ChristianSilvermoon I have Ubuntu installed in termux, LXDE installed and just installed Xserver XADL apk as well, how do you use the Xserver app to view my Ubuntu in termux? Thank you for your help

I also need help on this
